import { ModeId } from "./modes";
import { extOf } from "./mockFiles";

// A deterministic, template-based "patch" for the mock Apply-to-File loop.
// No real AI / diff engine — just safe, local content transforms driven by the
// active mode + current file content + file name.

export type ForgePatch = { summary: string; after: string };

function scaffoldFor(fileName: string): string {
  const ext = extOf(fileName);
  const raw = fileName.replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9]/g, "");
  const fn = raw || "main";
  const comp = raw ? raw.charAt(0).toUpperCase() + raw.slice(1) : "Component";

  if (ext === "tsx" || ext === "jsx") {
    return `export default function ${comp}() {\n  return (\n    <div>\n      ${comp}\n    </div>\n  );\n}\n`;
  }
  if (ext === "ts" || ext === "js") {
    return `export function ${fn}() {\n  // implementation goes here\n}\n`;
  }
  if (ext === "py") {
    return `def main():\n    pass\n\n\nif __name__ == "__main__":\n    main()\n`;
  }
  return `// ${fileName}\n// Scaffold generated by Tavronus Forge.\n`;
}

export function buildPatch(mode: ModeId, content: string, fileName: string): ForgePatch {
  const has = (re: RegExp) => re.test(content);

  // 1. Empty file → starter scaffold by extension.
  if (!content.trim()) {
    return { summary: "Insert starter scaffold.", after: scaffoldFor(fileName) };
  }

  // 2. Debug + useSearchParams without a client directive → add "use client".
  if (mode === "debug" && has(/\buseSearchParams\b/) && !has(/^\s*["']use client["']/m)) {
    return {
      summary: "Add client component directive for useSearchParams context.",
      after: `"use client";\n\n${content}`,
    };
  }

  // 3. console.log present → strip debug log lines.
  if (has(/console\.log/)) {
    const after = content
      .split("\n")
      .filter((line) => !/console\.log\s*\(/.test(line))
      .join("\n");
    return { summary: "Remove debug console.log statements.", after };
  }

  // 4. TODO/FIXME present → normalize to a neutral review comment.
  if (has(/\b(?:TODO|FIXME)\b/)) {
    const after = content.replace(
      /^.*\b(?:TODO|FIXME)\b.*$/gm,
      "// Reviewed by Tavronus Forge: follow-up required"
    );
    return { summary: "Normalize TODO/FIXME comments.", after };
  }

  // 5. Fallback → prepend a Forge review note.
  return {
    summary: "Add Forge review note.",
    after: `// Forge suggestion: review this file against the generated artifact.\n${content}`,
  };
}
